WorkDirectory : C:\Users\JOKOI\Desktop\1
BitMap : 8191
InheritSource :
  - C:\Users\JOKOI\Desktop\copy\report\[2022-01-16 ※ 23-18-01].txt
  - C:\Users\JOKOI\Desktop\copy\report\[2022-01-16 ※ 23-36-27].txt